### ISSUE TITLE
Locking the vehicle and pressing V renders vehicle unaccessible to everyone

### ISSUE THREAD

**Issue by AgentRev** [A3Armory/A3A_A3Wasteland_Sock.Stratis#1]
As the title says, if you have the Lock vehicle action selected while inside the vehicle, and you press spacebar to trigger the action, while also pressing V simultaneously to get out, the vehicle remains locked permanently and nobody can access it.

Maybe save the player UID of whoever triggered the lock, and allow him to unlock the vehicle from the outside in case this happens. Of course, the vehicle should remain lockable from the inside only.

**Comment by Gigatek1** [comment]
When I get sometime later I will test this with a friend and comment more about this. I don't think we have heard anything about this because anyone with a toolkit can do a picklock and it probably resets after a restart.

**Comment by AgentRev** [comment]
Oh there's picklock? I didn't know.

**Comment by Gigatek1** [comment]
It's something I added awhile back.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Stratis/blob/master/addons/scripts/lockPick.sqf
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Stratis/blob/master/client/functions/playerActions.sqf#L27

**Comment by Gigatek1** [comment]
This issue was moved to A3Armory/A3A_A3Wasteland_Sock.Altis#8
